stages:
  - build
  - package
  - deploy

variables:
  KUBE_CONTEXT: hydropersonal/poctes/docs:cloud

.use_context: &use_context
  - kubectl config get-contexts
  - kubectl config use-context "$KUBE_CONTEXT"

# Build the documentation website
build:
  image: node:20-slim
  stage: build
  script:
    - yarn install
    - yarn build
  artifacts:
    untracked: true
  when: always
  tags:
    - $RUNNERTAG

# Create a containter with the documentation
docker:
  image: docker:latest
  stage: package
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY_IMAGE
    - docker build -t "$CI_REGISTRY_IMAGE/documentation:latest" --push .
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a build of the Docker image
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  tags:
    - $RUNNERTAG

# Deploy documentation on Gitlab pages
pages:
  image: node:20.2-slim
  stage: deploy
  script:
    - mkdir ./public
    - cp -r "./build/"* "./public"
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  dependencies:
    - build
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  tags:
    - $RUNNERTAG

# Deploy edge documentation (Docusaurus) container in Kubernetes cluster
edge-documentation-vcluster:
  stage: deploy
  image:
    name: dtzar/helm-kubectl
    entrypoint: [""]
  script:
    - *use_context
    - kubectl apply -f ./deploy/edge-documentation.yaml
    - kubectl get pods -n poctes-system
  rules:
    - when: manual
      allow_failure: true
  tags:
    - $RUNNERTAG


# Deploy edge documentation (Docusaurus) container in Kubernetes cluster
edge-documentation-prince:
  stage: deploy
  image:
    name: openbayes/docusaurus-prince-pdf
    # entrypoint: [""]
  script:
    - ls
  rules:
    - when: manual
      allow_failure: true
  tags:
    - $RUNNERTAG

# docker run --rm -it --init -v $(pwd)/pdf:/app/pdf openbayes/docusaurus-prince-pdf -u https://docusaurus.io/docs/