# The Docker image that will be used to build your app
image: node:20.2-slim
# Functions that should be executed before the build script is run
before_script:
  - mkdir ./public
pages:
  script:
    - yarn install
    - yarn build
    - cp -r "./build/"* "./public"
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
